### ISSUE TITLE
Scenarios under Rules are not recognized

### ISSUE THREAD

**Issue by adsTestin** [Balrog994/cucumber-test-runner#2]
Hello, 
Thanks for this extention. 

When the feature file contains rule(s), the extention doesn't recognize scenarios! 

When I comment Rules, all works fine! 

Have a nice day!

**Comment by Balrog994** [comment]
Hi,
thanks for your feedback 😄 

I'll take a look at it, can you in the meantime provide a simple file to reproduce the problem?

Thank you

**Comment by adsTestin** [comment]
Feature: Test Background Feature
Description: The purpose of this feature is to test scenarios under rule


Rule: Check rule 1
Scenario: Search a product and add the first product to the User basket
	Given User search for Lenovo Laptop
	When Add the first laptop that appears in the search result to the basket
	Then User basket should display with added item

Scenario: Navigate to a product and add the same to the User basket
	Given User navigate for Lenovo Laptop
	When Add the laptop to the basket
	Then User basket should display with added item
	
Rule: Check rule 2
Scenario: Search a product and add the first product to the User basket
	Given User search for Lenovo Laptop
	When Add the first laptop that appears in the search result to the basket
	Then User basket should display with added item
